blank_issues_enabled: false
contact_links:
  - name: GitHub Actions Community Forum
    url: https://github.community/t5/GitHub-Actions/bd-p/actions
    about: Please ask questions about GitHub Actions here.
  - name: The Rust Programming Language Forum
    url: https://users.rust-lang.org/
    about: Please ask questions about mdBook and Rust here.
