name: Release

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Install hub
        run: |
          HUB_VERSION="2.13.0"
          HUB_NAME="hub-linux-amd64-${HUB_VERSION}"
          HUB_TARBALL="${HUB_NAME}.tgz"
          wget -q "https://github.com/github/hub/releases/download/v${HUB_VERSION}/${HUB_TARBALL}"
          tar -zxvf "./${HUB_TARBALL}"
          mkdir ~/bin
          cp "./${HUB_NAME}/bin/hub" ~/bin/
          echo "::add-path::~/bin/"
          rm -rf "./${HUB_NAME}" "./${HUB_TARBALL}"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          git log -n 1 -p ./CHANGELOG.md | grep "^+" | sed -e '1d' | sed -e 's/^+//g' > ./release_notes.md
          sed -i "1iRelease ${TAG_NAME}\n" ./release_notes.md
          hub release create \
            --draft \
            --prerelease \
            --file ./release_notes.md \
            "${TAG_NAME}"
