name: 'Test'

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore:
      - 'release-*'
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
      id: nvm

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm ci

    - run: npm run format:check

    - run: npm run lint

    - run: npm test

    - run: npm run build

    - name: Upload build assets
      uses: actions/upload-artifact@v1
      with:
        name: build-assets
        path: lib/index.js

    - name: Upload test coverage
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: coverage


  test-prod:
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'macos-latest', 'windows-latest']
        mdbook-version: ['latest', '0.3.4']
    steps:

    - uses: actions/checkout@v2

    - run: mkdir ./lib

    - name: Download build assets
      uses: actions/download-artifact@v1
      with:
        name: build-assets
        path: lib/index.js

    - name: Setup Git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Commit build assets
      run: |
        git add ./lib/index.js
        git commit -m "ci: Add build assets"

    - name: Test action
      uses: ./
      with:
        mdbook-version: ${{ matrix.mdbook-version }}
